Sds.ReceiptShare.Ui.Web/Models/Group/AddCurrenciesViewModel.cs
using System.Collections.Generic;

namespace Sds.ReceiptShare.Ui.Web.Models.Group
{
    public class AddCurrenciesViewModel
    {
        public int GroupId { get; set; }
        public List<CurrencyCheckboxListItem> CurrencyCheckboxList { get; set; }
    }
}

Sds.ReceiptShare.Ui.Web/Models/Group/AddMembersViewModel.cs
using System.Collections.Generic;

namespace Sds.ReceiptShare.Ui.Web.Models.Group
{
    public class AddMembersViewModel
    {
        public string EmailAddresses { get; set; }
        public int GroupId { get; internal set; }
    }
}

Sds.ReceiptShare.Ui.Web/Models/Group/AddPurchaseViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sds.ReceiptShare.Ui.Web.Models.Group
{
    public class AddPurchaseViewModel
    {
        public string Name { get; set; }
        public double Value { get; set; }
        public int Currency { get; set; }
        public IEnumerable<SelectListItem> Currencies { get; set; }
        public CheckboxList Beneficiaries { get; set; }
        public string Purchaser { get; set; }
        public IEnumerable<SelectListItem> Members { get; set; }
    }
}

Sds.ReceiptShare.Ui.Web/Models/Group/CheckboxList.cs
using System.Collections.Generic;

namespace Sds.ReceiptShare.Ui.Web.Models.Group
{
    public class CheckboxList
    {
        public List<CheckboxListItem> Items { get; set; }
    }
}

Sds.ReceiptShare.Ui.Web/Models/Group/CheckboxListItem.cs
namespace Sds.ReceiptShare.Ui.Web.Models.Group
{
    public class CheckboxListItem
    {
        public string Value { get; set; }
        public string Text { get; set; }
        public bool IsChecked { get; set; }
    }
}

Sds.ReceiptShare.Ui.Web/Models/Group/CreateViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sds.ReceiptShare.Ui.Web.Models.Group
{
    public class CreateViewModel
    {
        public string Name { get; set; }

        public List<string> UserIds { get; set; }

        public IEnumerable<SelectListItem> Currencies { get; internal set; }
                
        public int PrimaryCurrency { get; set; }
    }
}

Sds.ReceiptShare.Ui.Web/Models/Group/Currency.cs
using System;

namespace Sds.ReceiptShare.Ui.Web.Models.Group
{
    public class Currency
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Symbol { get; set; }
        public double Rate { get; internal set; }
        public bool IsPrimary { get; internal set; }
    }
}

Sds.ReceiptShare.Ui.Web/Models/Group/CurrencyCheckboxListItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sds.ReceiptShare.Ui.Web.Models.Group
{
    public class CurrencyCheckboxListItem
    {
        public Currency Currency { get; set; }
        public double Rate { get; set; }
        public bool Checked { get; set; }
    }
}

Sds.ReceiptShare.Ui.Web/Models/Group/DetailsViewModel.cs
using System;
using System.Collections.Generic;

namespace Sds.ReceiptShare.Ui.Web.Models.Group
{
    public class DetailsViewModel
    {
        public string Name { get; set; }
        public int Id { get; set; }
        public DateTime CreatedOn { get; set; }
        public List<Member> Members { get; set; }
        public List<Purchase> Purchases { get; set; }
        public List<Currency> Currencies { get; internal set; }
        public IEnumerable<Repayment> Repayments { get; internal set; }
        public Currency PrimaryCurrency { get; internal set; }
    }
}

Sds.ReceiptShare.Ui.Web/Models/Group/GroupMember.cs
namespace Sds.ReceiptShare.Ui.Web.Models.Group
{
    public class GroupMember
    {
        public string UserId { get; set; }
        public string Name { get; set; }
        public bool IsAdministrator { get; set; }
    }
}

Sds.ReceiptShare.Ui.Web/Models/Group/Member.cs
namespace Sds.ReceiptShare.Ui.Web.Models.Group
{
    public class Member
    {
        public string UserId { get; set; }
        public string Name { get; set; }
        public double Balance { get { return TotalContribution - TotalBenefit; } }
        public bool IsAdministrator { get; set; }
        public double TotalBenefit { get; internal set; }
        public double TotalContribution { get; internal set; }
    }
}

Sds.ReceiptShare.Ui.Web/Models/Group/Purchase.cs
using System;

namespace Sds.ReceiptShare.Ui.Web.Models.Group
{
    public class Purchase
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Currency Currency { get; set; }
        public double Value { get; set; }
        public string PurchasedBy { get; set; }
        public DateTime Date { get; set; }
        public PurchaseBeneficiaries Beneficiaries { get; internal set; }
    }
}

Sds.ReceiptShare.Ui.Web/Models/Group/PurchaseBeneficiaries.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Sds.ReceiptShare.Core.ExtensionMethods;

namespace Sds.ReceiptShare.Ui.Web.Models.Group
{
    public class PurchaseBeneficiaries
    {
        public IEnumerable<PurchaseBeneficiary> Beneficiaries { get; set; }

        public PurchaseBeneficiaries(ICollection<string> names, double amount)
        {
            var share = amount / names.Count;
            Beneficiaries = names.Select(s => new PurchaseBeneficiary { Amount = share.Round(), Name = s });
        }
    }
}

Sds.ReceiptShare.Ui.Web/Models/Group/PurchaseBeneficiary.cs
using System;

namespace Sds.ReceiptShare.Ui.Web.Models.Group
{
    public class PurchaseBeneficiary
    {
        public string Name { get; set; }
        public double Amount { get; set; }
    }
}

Sds.ReceiptShare.Ui.Web/Models/Group/Repayment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sds.ReceiptShare.Ui.Web.Models.Group
{
    public class Repayment
    {
        public string Payer { get; internal set; }
        public string Recipient { get; internal set; }
        public double Value { get; internal set; }
    }
}

Sds.ReceiptShare.Ui.Web/Controllers/GroupController.cs
using Microsoft.AspNetCore.Mvc;
using Sds.ReceiptShare.Ui.Web.Models.Group;
using Sds.ReceiptShare.Logic.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Sds.ReceiptShare.Logic.Managers;
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sds.ReceiptShare.Logic.Models.Group;
using Sds.ReceiptShare.Logic.Models;
using Sds.ReceiptShare.Core.ExtensionMethods;

namespace Sds.ReceiptShare.Ui.Web.Controllers
{
    [Authorize]
    public class GroupController : Controller
    {
        private readonly IGroupManager _groupManager;
        private readonly ApplicationUserManager _userManager;
        private readonly ILookupManager _lookupManager;

        public GroupController(IGroupManager groupManager, ApplicationUserManager userManager, ILookupManager lookupManager)
        {
            _groupManager = groupManager;
            _userManager = userManager;
            _lookupManager = lookupManager;            
        }


        /// <summary>
        /// TODO: I think this ought to be in the manager classes (along with the isAdmin check) so that any calls to those 
        /// methods are secured correctly. Perhaps they could throw a custom exception back to here which will result in the controller 
        /// method returning an UnauthorizedResult.
        /// </summary>
        /// <param name="groupId"></param>
        /// <returns></returns>
        private bool IsInGroup(int groupId)
        {
            var userId = HttpContext.User.Claims.First(s => s.Type == System.Security.Claims.ClaimTypes.NameIdentifier).Value;
            return _userManager.IsInGroup(userId, groupId);
        }

        private bool IsAdministrator(int groupId)
        {
            var userId = HttpContext.User.Claims.First(s => s.Type == System.Security.Claims.ClaimTypes.NameIdentifier).Value;
            return _userManager.IsAdministrator(userId, groupId);
        }

        public IActionResult Index(int id)
        {
            // If no id is provided, then FUCK THIS. You're going home.
            if (id == 0) return Redirect("/");

            // You better be in the group too. TODO: I've tried to implement this as an Auth module but it was just too flaky. What else can we do?
            if (!IsInGroup(id)) return new UnauthorizedResult();
 
            var group = _groupManager.GetDetails(id);
            if (group == null) return new NotFoundResult();

            var members = _groupManager.GetMembersWithSummary(id);
            var purchases = _groupManager.GetPurchases(id);
            var currencies = _groupManager.GetCurencies(id, true);
            var repayments = _groupManager.CalculateRepayments(id);
            var model = new DetailsViewModel()
            {
                Id = group.Id,
                Name = group.Name,
                CreatedOn = group.Created,
                Members = members?.Select(s => new Member
                {
                    Name = s.Name,
                    UserId = s.Id,
                    IsAdministrator = s.IsAdministrator,
                    TotalBenefit = s.TotalBenefit.Round(),
                    TotalContribution = s.TotalContribution.Round() }).ToList(),
                PrimaryCurrency = new Currency
                {
                    Id = group.PrimaryCurrency.Id,
                    Name = group.PrimaryCurrency.Name,
                    Symbol = group.PrimaryCurrency.Symbol,
                    Rate = 1,
                    IsPrimary = true
                },
                Currencies = currencies.Select(s=> new Currency { Id = s.Id, Name = s.Name, Symbol = s.Symbol, Rate = s.Rate }).ToList(),            
                Purchases = purchases.Select(s => new Purchase
                {
                    Name = s.Description,
                    Value = s.Amount.Round(),
                    PurchasedBy = s.PurchaserName,
                    Id = s.Id,
                    Date = s.Date,
                    Currency = new Currency { Name = s.Currency.Name, Symbol = s.Currency.Symbol },
                    Beneficiaries = new PurchaseBeneficiaries(s.Beneficiaries, s.Amount.Round())
                }).OrderByDescending(s => s.Date).ToList(),
                Repayments = repayments.Select(s => new Repayment() { Payer = s.PayerName, Recipient = s.RecipientName, Value = s.Value.Round()})
            };
            
            return View(model);
        }

        public IActionResult Create()
        {
            var currencies = _lookupManager.GetAllCurrencies();

            return View(new CreateViewModel()
            {
                Currencies = currencies.Select(s => new SelectListItem { Value = s.Id.ToString(), Text = $"{s.Name} - {s.Symbol}", Selected = s.Symbol == "£" })
            });
        }

        [HttpPost]
        public IActionResult Create(CreateViewModel model)
        {
            var user = _userManager.GetUserAsync(HttpContext.User).Result;
            var primaryCurrencyId = model.PrimaryCurrency;

            var group = new GroupAdd()
            {
                Name = model.Name,
                CreatorId = user.Id,
                PrimaryCurrencyId = primaryCurrencyId
            };

            var id = _groupManager.Add(group);
            return RedirectToAction("Index", new { id = id });
        }

        [HttpGet]
        public IActionResult AddMembers(int id)
        {
            if (!IsAdministrator(id)) return new UnauthorizedResult();

            var members = _groupManager.GetMembers(id);
            var user = _userManager.GetUserAsync(HttpContext.User).Result;

            return View(new AddMembersViewModel()
            {
                GroupId = id,
                EmailAddresses = string.Join(",", members.Where(s=>s.Email != user.Email).Select(s => s.Email).ToArray())
            });
        }

        [HttpPost()]
        public IActionResult AddMembers(int id, AddMembersViewModel model)
        {
            if (!IsAdministrator(id)) return new UnauthorizedResult();
            _groupManager.ManageMembers(id, model.EmailAddresses.Split(",").Where(s => !string.IsNullOrEmpty(s)).ToList());
            return RedirectToAction("Index", new { id = id });
        }

        [HttpGet]
        public IActionResult AddCurrencies(int id)
        {
            if (!IsAdministrator(id)) return new UnauthorizedResult();

            var currencies = _lookupManager.GetAllCurrencies();
            var selectedCurrencies = _groupManager.GetCurencies(id);
            var checkboxList = new List<CurrencyCheckboxListItem>();

            foreach (var item in currencies)
            {
                var selectedCurrency = selectedCurrencies.SingleOrDefault(s => s.Id == item.Id);
                checkboxList.Add(new CurrencyCheckboxListItem()
                {
                    Checked = selectedCurrency != null,
                    Rate = selectedCurrency?.Rate ?? 0,
                    Currency = new Currency { Id = item.Id, Name = item.Name, Symbol = item.Symbol, }
                });
            }

            var model = new AddCurrenciesViewModel()
            {
                GroupId = id,
                CurrencyCheckboxList = checkboxList
            };

            return View(model);
        }

        [HttpPost()]
        public IActionResult AddCurrencies(int id, AddCurrenciesViewModel model)
        {
            if (!IsAdministrator(id)) return new UnauthorizedResult();

            _groupManager.UpdateCurrencies(id, model.CurrencyCheckboxList.Where(s => s.Checked).Select(s =>
                 new GroupCurrency()
                 {
                     Id = s.Currency.Id,
                     Rate = s.Rate
                 }));

            return RedirectToAction("Index", new { id = id });
        }

        [HttpGet]
        public IActionResult AddPurchase(int id)
        {
            if (!IsInGroup(id)) return new UnauthorizedResult();

            var members = _groupManager.GetMembers(id);
            var currencies = _groupManager.GetCurencies(id);

            var model = new AddPurchaseViewModel()
            {
                Beneficiaries = new CheckboxList
                {
                    Items = members.Select(s => new CheckboxListItem { Value = s.Id, Text = s.Name }).ToList()
                },
                Currencies = currencies.Select(s => new SelectListItem { Text = s.Name, Value = s.Id.ToString() }),
                Members = members.Select(s => new SelectListItem { Value = s.Id, Text = s.Name })
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult AddPurchase(int id, AddPurchaseViewModel model)
        {
            if (!IsInGroup(id)) return new UnauthorizedResult();

            var purchase = new Logic.Models.Purchase.PurchaseAddUpdate
            {
                Amount = model.Value,
                Description = model.Name,
                PurchaserId = model.Purchaser,
                CurrencyId = model.Currency,
                GroupId = id,
                Beneficiaries = model.Beneficiaries.Items.Where(s => s.IsChecked).Select(s => s.Value).ToList()
            };

            _groupManager.AddPurchase(purchase);

            return RedirectToAction("Index", new { id = id });
        }


        [HttpGet]
        public IActionResult EditPurchase(int id, int purchaseId)
        {
            if (!IsInGroup(id)) return new UnauthorizedResult();

            var model = new { };
            return View(model);
        }
    }
}

Sds.ReceiptShare.Ui.Web/Views/Group/AddCurrencies.cshtml
@model Sds.ReceiptShare.Ui.Web.Models.Group.AddCurrenciesViewModel

@{
    ViewData["Title"] = "AddCurrencies";
}

<h2>AddCurrencies</h2>

<h4>AddCurrenciesViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddCurrencies">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @if (@Model.CurrencyCheckboxList != null && @Model.CurrencyCheckboxList.Count() > 0)
            {
                for (int i = 0; i < @Model.CurrencyCheckboxList.Count(); i++)
                {
                    <div>
                        <input asp-for="@Model.CurrencyCheckboxList[i].Checked" type="checkbox" />
                        <label asp-for="@Model.CurrencyCheckboxList[i].Checked">@Model.CurrencyCheckboxList[i].Currency.Name</label>
                        <input type="number" step="0.01" asp-for="@Model.CurrencyCheckboxList[i].Rate" value="@Model.CurrencyCheckboxList[i].Rate" />
                        
                        @*If these are not included, all OptionIds become 0 and all OptionName becomes null*@
                        @Html.HiddenFor(x => @Model.CurrencyCheckboxList[i].Currency.Id)
                        @Html.HiddenFor(y => @Model.CurrencyCheckboxList[i].Currency.Name)
                    </div>
                }
            }
            @*@if (@Model.CurrencyCheckboxList != null && @Model.CurrencyCheckboxList.Any())
            {
                foreach(var item in @Model.CurrencyCheckboxList)
                {
                    <div>
                        <input asp-for="@item.Checked" type="checkbox" />
                        <label asp-for="@item.Checked">@item.Currency.Name</label>
                        
                        @Html.HiddenFor(x => item.Currency.Id)
                        @Html.HiddenFor(y => item.Currency.Name)
                    </div>
                }
            }*@
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Sds.ReceiptShare.Ui.Web/Views/Group/AddMembers.cshtml
@model Sds.ReceiptShare.Ui.Web.Models.Group.AddMembersViewModel
@{
    ViewData["Title"] = "Add members to the group";
}

<h2>Add Members</h2>
<hr />
<div class="row" onload="loadMembers()">
    <div class="col-md-4">
        <div class="form-group">
            <label for="AddEmail">Add member</label>
            <input id="AddEmail" type="email" placeholder="Email address" class="input-sm" inputmode="email" />
            <input type="button" value="Add" class="btn-link" onclick="addMember()" />
            <label id="AddEmailValidator" class="alert-danger" style="display:none;">Please enter a valid email address for a member not already listed.</label>
        </div>

        <div class="form-group">
            <div id="Members" class="btn-group-vertical">Loading members...</div>
        </div>

        <div class="form-group">
            <form asp-action="AddMembers">
                @Html.HiddenFor(model => model.EmailAddresses)
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn-primary btn-sm" />
                </div>
            </form>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to group</a>
</div>

@section Scripts {
    <script type="text/javascript">
        var counter = 0;
        var template = $('#template').html();

        $(document).ready(function () {

            var rendered = "";
            var emailAddresses = $('#EmailAddresses').val();
            if (emailAddresses !== '') {
                var members = emailAddresses.split(',');

                Mustache.parse(template);
                members.forEach(function (index) {
                    counter++;
                    rendered += Mustache.render(template, { email: index, id: counter });
                });

                $('#Members').html(rendered);
            } else {
                $('#Members').html($('#nomembersTemplate').html());
            }
        });

        function deleteMember(id) {
            var item = $('#member-' + id);
            var email = item.data("email");
            item.remove();
            var emails = $('#EmailAddresses').val().replace(email, "");
            $('#EmailAddresses').val(emails);
        }

        function addMember() {
            var emailBox = $('#AddEmail');
            var membersList = $('#Members');
            var emailAddressesHidden = $('#EmailAddresses');
            email = emailBox.val();

            if (validateEmail(email) && emailAddressesHidden.val().indexOf(email) == -1) {
                $('#AddEmailValidator').hide()
                $('#noMembersWarning').hide()
                emailBox.val('');

                counter++;

                var element = Mustache.render(template, { email: email, id: counter });
                membersList.append(element);
                var emails = emailAddressesHidden.val() + ',' + email;
                emailAddressesHidden.val(emails)
            } else {
                $('#AddEmailValidator').show()
            }

            emailBox.focus();           
        }

        function validateEmail($email) {
            var emailReg = /^([a-zA-Z0-9_.+-])+\@@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
            return emailReg.test($email);
        }
    </script>
}

<script id="template" type="x-tmpl-mustache">
    <div id="member-{{id}}" class="btn-info" style="padding:5px; margin:2px;" data-email="{{email}}">
        {{email}} <i id="member-{{id}}-delete" class="fa fa-trash" style="float:right; padding:3px 0 0 10px;" aria-hidden="true" onclick="deleteMember({{id}})"></i>
    </div>
</script>

<script id="nomembersTemplate" type="x-tmpl-mustache">
    <div id="noMembersWarning" class="bg-warning warning">No one else is in your group yet!</div>
</script>

Sds.ReceiptShare.Ui.Web/Views/Group/AddPurchase.cshtml
@model Sds.ReceiptShare.Ui.Web.Models.Group.AddPurchaseViewModel
@{
    ViewData["Title"] = "AddPurchase";
}
<h2>AddPurchase</h2>
<h4>AddPurchaseViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddPurchase">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Currency" class="control-label"></label>
                <select asp-for="Currency" asp-items="Model.Currencies" class="form-control"></select>
                <span asp-validation-for="Currency" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Purchaser" class="control-label"></label>
                <select asp-for="Purchaser" asp-items="Model.Members" class="form-control"></select>
                <span asp-validation-for="Purchaser" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Beneficiaries" class="control-label"></label>
                @if (@Model.Beneficiaries != null && @Model.Beneficiaries.Items.Count() > 0)
                {
                    for (int i = 0; i < @Model.Beneficiaries.Items.Count(); i++)
                    {
                        <div>
                            <input asp-for="@Model.Beneficiaries.Items[i].IsChecked" type="checkbox" class="checkbox-inline"/>
                            <label asp-for="@Model.Beneficiaries.Items[i].IsChecked" class="input-sm">@Model.Beneficiaries.Items[i].Text</label>
                            @*If these are not included, all OptionIds become 0 and all OptionName becomes null*@
                            @Html.HiddenFor(x => @Model.Beneficiaries.Items[i].Value)
                            @Html.HiddenFor(y => @Model.Beneficiaries.Items[i].Text)
                        </div>
                    }
                }
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Sds.ReceiptShare.Ui.Web/Views/Group/Create.cshtml
@model Sds.ReceiptShare.Ui.Web.Models.Group.CreateViewModel

@{
    ViewData["Title"] = "View";
}

<h2>View</h2>

<h4>Create a mew group</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="View">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Currencies" class="control-label"></label>
                <select asp-for="PrimaryCurrency" asp-items="Model.Currencies" class="form-control"></select>
                <span asp-validation-for="PrimaryCurrency" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" asp-controller="Group" asp-action="Create" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Home">Back to List</a>
</div>

Sds.ReceiptShare.Ui.Web/Views/Group/Index.cshtml
@model Sds.ReceiptShare.Ui.Web.Models.Group.DetailsViewModel
@{
    ViewData["Title"] = "Index";
}
<h2>@Model.Name</h2>
<a asp-action="Index" asp-controller="Home">Back to Groups</a>
<div class="panel">
    <h4>Purchases Overview</h4>
    <div class="panel-body" style="overflow-x:scroll;">
        <table class="table table-responsive table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">Purchaser</th>
                    <th scope="col">Purchase Description</th>
                    <th scope="col">Currency</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Date</th>
                    @foreach (var item in Model.Members)
                    {
                        <th>
                            @if (item.IsAdministrator)
                            {
                                <sub>Admin</sub><br />
                            }
                            @item.Name
                        </th>
                    }
                    <td colspan="2"></td>
                </tr>
            </thead>
            @foreach (var item in Model.Purchases)
            {
                var beneficiaries = item.Beneficiaries.Beneficiaries;
                var amount = beneficiaries.First().Amount;
                <tr>
                    <td class="col-ms-2">@item.PurchasedBy </td>
                    <td class="col-ms-2">@item.Name </td>
                    <td class="col-ms-2">@item.Currency.Symbol </td>
                    <td class="col-ms-2">@item.Value </td>
                    <td class="col-ms-2">@item.Date.Date </td>
                    @foreach (var person in Model.Members)
                    {
                        <td>
                            @if (beneficiaries.Select(s => s.Name).ToList().Contains(person.UserId))
                            {
                                <div> @amount </div>
                            }
                        </td>
                    }
                    <td>Delete</td>
                    <td>Edit</td>
                </tr>
            }
            <tfoot>
                <tr>
                    <th colspan="2">Totals</th>
                    <td colspan="2">@Model.PrimaryCurrency.Symbol@Model.Purchases.Select(s => s.Value / 1).Sum()</td>
                    <th>Total Benefit</th>
                    @foreach (var item in Model.Members)
                    {
                        <td>@Model.PrimaryCurrency.Symbol@item.TotalBenefit</td>

                    }
                    <td colspan="2"></td>
                </tr>
                <tr>
                    <td colspan="4"></td>
                    <th>Total Contribution</th>
                    @foreach (var item in Model.Members)
                    {
                        <td>@Model.PrimaryCurrency.Symbol@item.TotalContribution</td>
                    }
                    <td colspan="2"></td>
                </tr>
                <tr>
                    <td colspan="4"></td>
                    <th>Balance</th>
                    @foreach (var item in Model.Members)
                    {
                        <td class="@(item.Balance > 0 ? "label-success" :"label-danger")">@Model.PrimaryCurrency.Symbol@item.Balance</td>
                    }
                    <td colspan="2"></td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="panel-footer">
        <a asp-action="AddPurchase" asp-route-id="@Model.Id" class="btn-lg">Add Purchase</a><br />
        <a asp-action="AddMembers" asp-route-id="@Model.Id" class="btn-lg">Manage Members</a><br />
    </div>
</div>
<div class="panel">
    <div class="panel-heading h4">Repayments</div>
    <div class="panel-body">
        @foreach (var item in Model.Repayments)
        {
        <div class="row">
            <span class="col-md-3 text-right">@item.Payer</span>
            <span class="col-md-1 text-center">pays</span>
            <span class="col-md-3">@item.Recipient</span>
            <span class="col-md-2 text-info">@Model.PrimaryCurrency.Symbol@item.Value</span>
        </div>
        }
    </div>
</div>
<div class="panel">
    <div class="panel-heading h4">
        @Html.DisplayNameFor(model => model.Currencies)
    </div>
    <div class="panel-body">
        <div class="row">
            <span class="col-md-2">@Model.PrimaryCurrency.Name<span>s</span> &#40;@Model.PrimaryCurrency.Symbol&#41;</span>
            <span class="label-info col-md-2">
                primary
            </span>
        </div>
        @foreach (var item in Model.Currencies)
        {
            <div class="row">
                <span class="col-md-2">@item.Name<span>s</span> &#40;@item.Symbol&#41;</span>
                <span class="label-warning col-md-2">@item.Symbol@item.Rate to @Model.PrimaryCurrency.Symbol<span>1</span></span>
            </div>
        }
    </div>
    <a asp-action="AddCurrencies" asp-route-id="@Model.Id" class="btn-lg">Manage Currencies</a>
</div>